// Docs: @docs/7.extension.md
// Docs: @docs/4.agents/2.pi/3.on-device-models.md
/**
 * wllama, made to fit an MV3 page. Two vite plugins, both build time.
 *
 * wllama never loads a worker from a file. It joins the emscripten glue and its
 * own worker code into one string at run time and starts it as a `blob:` url —
 * `createWorker()` in the package. A regular page allows that. An extension
 * page does not: a worker script is matched against `worker-src`, which falls
 * back to `script-src 'self'`, and `blob:` is not `'self'`. The MV3 policy
 * cannot be widened either, so this is not a manifest setting that was missed.
 *
 * So the build writes the same worker out as a file, which `'self'` covers, and
 * the run time is pointed at it. `wllamaAssets()` writes the files;
 * `wllamaWorkers()` rewrites `createWorker()` to call `worker.ts` beside this
 * one. Nothing is patched in `node_modules` — the rewrite is a transform, so an
 * update to wllama arrives through the lockfile like any other.
 *
 * Every read here asserts. A wllama that has moved one of these pieces fails
 * the build with the name of what moved, rather than shipping a panel whose
 * local models throw on the first turn.
 */
import { cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Plugin } from "vite";

import { ASSETS } from "./worker.ts";

const here = fileURLToPath(new URL(".", import.meta.url));

/** The installed package, found the way the panel's own import resolves it. */
const wllama = fileURLToPath(new URL(".", import.meta.resolve("@wllama/wllama/package.json")));

const read = (path: string): string => readFileSync(`${wllama}${path}`, "utf8");

let codes: string | undefined;

/**
 * One of the code strings the package generates from its own sources. They are
 * written by `scripts/build_worker.sh` as `JSON.stringify()` output, so the
 * literal is json and one line, whatever the file it was made from holds.
 */
function generated(name: string): string {
  codes ??= read("src/workers-code/generated.ts");
  const match = codes.match(new RegExp(`^export const ${name} = (".*");$`, "m"));
  if (!match) throw new Error(`wllama: ${name} is not in src/workers-code/generated.ts`);
  return JSON.parse(match[1]!) as string;
}

/**
 * The stub wllama puts in front of the glue, which stands `WebAssembly` in for
 * a runtime with no JSPI. It is a plain template literal in the bundle — the
 * one piece of the worker the package does not also ship as a file.
 */
function jspiStub(): string {
  const bundle = read("esm/index.js");
  const match = bundle.match(/var JSPI_STUB = `([^`]*)`/);
  if (!match) throw new Error("wllama: JSPI_STUB is not in esm/index.js");
  if (!match[1]!.includes("WebAssembly.Suspending")) {
    throw new Error("wllama: JSPI_STUB no longer stubs WebAssembly.Suspending");
  }
  return match[1]!;
}

/**
 * The worker the package would have built, with the one part it cannot know
 * ahead of time taken out.
 *
 * `moduleInit()` joins three pieces: the options of this run, the glue wrapped
 * in `wModuleInit()`, and the worker code. Only the first is decided at run
 * time, so it is read off the worker's own url here instead — the query the
 * panel puts there. The rest is fixed for a version and is what this writes.
 */
function llamaWorker(): string {
  const module = jspiStub() + generated("WLLAMA_EMSCRIPTEN_CODE");
  // Exactly what `moduleInit()` does, first match and all: the glue declares
  // `Module` and the worker returns the one the glue leaves behind.
  const main = module.replace("var Module", "var ___Module");

  const options = [
    "// Generated by extension/wllama/build.ts. Do not edit.",
    "// The options of this run, which the page puts on the worker's url.",
    'const RUN_OPTIONS = JSON.parse(new URL(self.location.href).searchParams.get("run") ?? "{}");',
  ].join("\n");

  const glue = `function wModuleInit() { ${main}; return Module; }`;
  return [options, glue, generated("LLAMA_CPP_WORKER_CODE")].join(";\n\n");
}

/** Writes the two workers and the wasm beside the bundle. */
export function wllamaAssets(outDir: string): Plugin {
  return {
    name: "wllama-assets",
    closeBundle() {
      const dir = `${outDir}/${ASSETS}`;
      mkdirSync(dir, { recursive: true });
      writeFileSync(`${dir}/llama.worker.js`, llamaWorker());
      writeFileSync(`${dir}/opfs.worker.js`, generated("OPFS_UTILS_WORKER_CODE"));
      cpSync(`${wllama}esm/wasm/wllama.wasm`, `${dir}/wllama.wasm`);
    },
  };
}

/** What the package does, and what it does here instead. */
const BLOB = `var createWorker = (workerCode) => {
  const workerURL = URL.createObjectURL(
    isString(workerCode) ? new Blob([workerCode], { type: "text/javascript" }) : workerCode
  );
  return new Worker(workerURL, { type: "module" });
};`;

const FILE = `var createWorker = (workerCode) => __agentakWorker(workerCode);`;

/**
 * Points `createWorker()` at the files above. The import is prepended rather
 * than reached through a global, so the two halves are one module graph and
 * a rename breaks the build.
 */
export function wllamaWorkers(): Plugin {
  const entry = `${here}worker.ts`;
  let rewritten = false;

  return {
    name: "wllama-workers",
    buildStart() {
      rewritten = false;
    },
    transform(code, id) {
      if (!id.includes("@wllama/wllama")) return null;
      if (!code.includes("var createWorker =")) return null;
      if (!code.includes(BLOB)) {
        throw new Error("wllama: createWorker() is not the blob url this build rewrites");
      }
      rewritten = true;
      return `import { __agentakWorker } from ${JSON.stringify(entry)};\n${code.replace(BLOB, FILE)}`;
    },
    // A rename would leave every branch above untaken, and the panel would ship
    // a wllama that starts a blob worker the policy stops on the first turn.
    buildEnd() {
      if (!rewritten) throw new Error("wllama: createWorker() was not found to rewrite");
    },
  };
}
